version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'gradle dependencies'
    commit-message:
      prefix: 'gradle'
    assignees:
      - 'gregoranders'
    target-branch: 'development'
