version: '2'
plugins:
  editorconfig:
    enabled: true
  checkstyle:
    enabled: false
    config:
      file: "config/checkstyle/checkstyle.xml"
  pmd:
    enabled: false
    config:
      file: "config/pmd/pmd-rules.xml"
  sonar-java:
    enabled: false
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.circleci'
  - '**/.vscode'
  - '**/build'
  - '**/temp'
  - '**/test'
  - '**/docs'
  - '**/gradle'
  - '**/gradlew'
  - '**/gradlew.bat'
  - '**/config'
