name: Feature CI
on:
  push:
    branches:
      - feature/*
env:
  CI: true
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '17.0.1' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute clean
        run: ./gradlew --info --stacktrace clean
      - name: Execute check
        run: ./gradlew --info --stacktrace check
      - name: Publish code coverage to codeclimate
        if: matrix.os == 'ubuntu-latest'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: ./gradlew --info --stacktrace check
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/jacocoTestReport.xml:jacoco
      - name: Publish code coverage to coveralls
        if: matrix.os == 'ubuntu-latest'
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: ./gradlew --info --stacktrace jacocoTestReport coveralls
      - name: Publish code coverage to codacy
        if: matrix.os == 'ubuntu-latest'
        env:
          CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: gregoranders
          CODACY_PROJECT_NAME: "com.github.gregoranders.template"
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r "${{github.workspace}}/build/reports/jacoco/jacocoTestReport.xml"
      - name: Execute build
        run: ./gradlew --info --stacktrace build
